NDIM=   10, IPS =   1, IRS =   0, ILP =   1
ICP =  [1, 6]
NTST=  150, NCOL=   4, IAD =   3, ISP =   1, ISW = 1, IPLT= 0, NBC= 0, NINT= 0
NMX=  100000, NPR=  2000, MXBF=  10, IID =   2, ITMX= 8, ITNW= 5, NWTN= 3, JAC=0
EPSL= 1e-09, EPSU = 1e-09, EPSS =1e-07
DS  =  0.0002, DSMIN= 0.00000001, DSMAX=   0.0001, IADS=   1
NPAR = 6, THL =  {11:0.0}, THU={1:1.0, 2:0.5, 3:1.0, 4:0.5}
parnames={1:'b',2:'D', 3:'a', 4:'e', 6:'phi'}
UZSTOP = {1: [-5, 1]}
